HOST:
  https://test.com/

EMAIL_INFO:
  user: 
  password: 
  host: smtp.126.com
ADDRESSEE:
  - 126@126.com
  - 
REDIS_INFO:
  port:
  password:
  host:
  db:
TEST_USER:
  moblie: 
  pw: 123
PRE_USER:
  moblie: 
  pw: 123

