HOST:
  https://www.baidu.com
EMAIL_INFO:
  user: tjd0314@126.com
  password: \%@)520tjD
  host: smtp.126.com
ADDRESSEE:
  - tjd0314@126.com
  - gideon0314@88.com
REDIS_INFO
  port:
  password:
  host:
  db:
