HOST:
  https://test.i.iglobalwin.com/
#  https://i.iglobalwin.com/
EMAIL_INFO:
  user: tjd0314@126.com
  password: VDOMGMTVNZEVGWHJ
  host: smtp.126.com
ADDRESSEE:
  - tjd0314@126.com
  - gideon0314@88.com
REDIS_INFO:
  port:
  password:
  host:
  db:
TEST_USER:
  moblie: 16602140314
  pw: 123
PRE_USER:
  moblie: 16602140314
  pw: 123

